#!/usr/bin/env python
"""Create compact project index files for the City Simulation Godot project."""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

from citysim_common import (
    ProjectFile,
    count_lines,
    extract_gdscript_symbols,
    iter_project_files,
    markdown_table,
    resolve_project_root,
    write_text,
)


INDEX_DIR = Path(".ai/project_index")


SYSTEM_DESCRIPTIONS = {
    "Actions": "Legacy/resource-style action classes for citizen behaviors.",
    "Entities": "Runtime domain objects: buildings, citizens, accounts, jobs, and benches.",
    "Simulation": "World orchestration, economy, time, bootstrap, navigation, GOAP, UI, debug, logging, and spatial helpers.",
    "Scenes": "Runtime and debug scenes/resources.",
    "config": "JSON tuning and rule data.",
    "environment": "Sky, day/night, and visual time systems.",
    "tools": "Headless probes, parse checks, audits, and regression tests.",
    "ImportedCitySource": "Imported source scenes/scripts. Treat as reference/import material unless the task targets it.",
}


def top_folder(rel: str) -> str:
    return rel.split("/", 1)[0]


def collect_class_rows(files: list[ProjectFile]) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for file in files:
        if file.extension != ".gd":
            continue
        symbols = extract_gdscript_symbols(file.path)
        class_name = ", ".join(symbols["class_names"]) or "-"
        extends = ", ".join(symbols["extends"]) or "-"
        rows.append((file.rel, class_name, extends))
    return rows


def find_duplicate_stems(files: list[ProjectFile]) -> list[tuple[str, int, str]]:
    groups: dict[str, list[str]] = defaultdict(list)
    for file in files:
        if file.extension not in {".gd", ".tscn", ".tres"}:
            continue
        groups[file.path.stem.lower()].append(file.rel)
    rows = []
    for stem, rels in sorted(groups.items()):
        if len(rels) > 1:
            rows.append((stem, len(rels), "<br>".join(rels[:8])))
    return rows[:40]


def write_files_index(root: Path, files: list[ProjectFile], index_dir: Path) -> None:
    by_extension = Counter(file.extension for file in files)
    by_folder = Counter(top_folder(file.rel) for file in files)
    largest = sorted(files, key=lambda item: item.size, reverse=True)[:20]
    largest_rows = [(file.rel, file.size, count_lines(file.path)) for file in largest]

    content = f"""# Files

Generated by `.ai/scripts/citysim_project_scan.py`.

## Root

- Project root: `{root}`
- Generated at: `{datetime.now().isoformat(timespec="seconds")}`
- Main scene: `Main.tscn`
- Project file: `project.godot`

## Counts By Extension

{markdown_table(["Extension", "Count"], sorted(by_extension.items()))}

## Counts By Top Folder

{markdown_table(["Folder", "Count"], sorted(by_folder.items()))}

## Important Folders

{markdown_table(["Folder", "Purpose"], sorted(SYSTEM_DESCRIPTIONS.items()))}

## Largest Indexed Files

{markdown_table(["Path", "Bytes", "Lines"], largest_rows)}

## Memory Notes

- Obsidian project memory lives in `C:\\dev\\projects\\ai_brain\\30_Projects\\Godot City Sim`.
- Qdrant collection: `city-sim-memory`.
- Ignore local/generated folders such as `.git`, `.godot`, `.claude`, `.ai/.cache`, `.ai/qdrant_storage`, `addons`, and `.import` files.
"""
    write_text(index_dir / "files.md", content)


def write_systems_index(files: list[ProjectFile], index_dir: Path) -> None:
    rows = collect_class_rows(files)
    rows_by_folder: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    for row in rows:
        rows_by_folder[top_folder(row[0])].append(row)

    sections = [
        "# Systems",
        "",
        "Generated by `.ai/scripts/citysim_project_scan.py`.",
        "",
        "Purpose: compact ownership map for common work areas.",
    ]
    for folder, description in sorted(SYSTEM_DESCRIPTIONS.items()):
        folder_rows = rows_by_folder.get(folder, [])[:35]
        sections.extend(["", f"## {folder}", "", description])
        if folder_rows:
            sections.extend(["", markdown_table(["Path", "class_name", "extends"], folder_rows)])
    write_text(index_dir / "systems.md", "\n".join(sections))


def write_duplicated_logic_index(files: list[ProjectFile], index_dir: Path) -> None:
    duplicate_stems = find_duplicate_stems(files)

    road_funcs = set()
    pedestrian_funcs = set()
    action_files = []
    goap_files = []
    for file in files:
        if file.rel.endswith("Simulation/Navigation/RoadGraph.gd"):
            road_funcs = set(extract_gdscript_symbols(file.path)["funcs"])
        if file.rel.endswith("Simulation/Navigation/PedestrianGraph.gd"):
            pedestrian_funcs = set(extract_gdscript_symbols(file.path)["funcs"])
        if file.rel.startswith("Actions/") and file.extension == ".gd":
            action_files.append(file.path.stem)
        if file.rel.startswith("Simulation/GOAP/") and file.extension == ".gd":
            goap_files.append(file.path.stem)

    shared_graph_funcs = sorted(road_funcs & pedestrian_funcs)
    action_words = {name.replace("Action", "").lower() for name in action_files}
    goap_words = {name.replace("Citizen", "").replace("Goap", "").lower() for name in goap_files}
    overlapping_behavior_words = sorted(action_words & goap_words)

    content = f"""# Duplicated Logic

Generated by `.ai/scripts/citysim_project_scan.py`.

Purpose: likely duplication areas to inspect before adding new code.

## Same File Stems

{markdown_table(["Stem", "Count", "Examples"], duplicate_stems) if duplicate_stems else "No duplicate stems found in indexed source files."}

## Navigation Graph Overlap

- Shared `RoadGraph` / `PedestrianGraph` function names: {", ".join(shared_graph_funcs) if shared_graph_funcs else "none detected"}.
- Do not duplicate graph search logic between road and pedestrian routing without a deliberate ownership decision.

## Citizen Behavior Overlap

- `Actions/*` files: {", ".join(sorted(action_files)) if action_files else "none detected"}.
- `Simulation/GOAP/*` files: {", ".join(sorted(goap_files)) if goap_files else "none detected"}.
- Overlapping behavior words: {", ".join(overlapping_behavior_words) if overlapping_behavior_words else "none detected"}.
"""
    write_text(index_dir / "duplicated_logic.md", content)


def write_unused_candidates_index(root: Path, files: list[ProjectFile], index_dir: Path) -> None:
    existing_local_dirs = []
    for rel in [".claude", ".godot", ".idea", ".obsidian", "AI", "AI_RuntimeTest"]:
        path = root / rel
        if path.exists():
            existing_local_dirs.append((rel, "local/generated or audit-only; do not scan by default"))

    candidate_names = []
    for file in files:
        lower = file.rel.lower()
        if "legacy" in lower or "old" in lower or "kopie" in lower or "_new" in lower:
            candidate_names.append((file.rel, "name suggests variant/legacy; verify references before deletion"))

    content = f"""# Unused Candidates

Generated by `.ai/scripts/citysim_project_scan.py`.

Purpose: candidate list only. Do not delete anything here without reference checks, scene checks, and tests.

## Local Or Generated Directories

{markdown_table(["Path", "Reason"], existing_local_dirs) if existing_local_dirs else "No local/generated directory candidates detected."}

## Name-Based Candidates

{markdown_table(["Path", "Reason"], candidate_names[:80]) if candidate_names else "No name-based candidates detected."}

## Required Follow-Up

- Run `.ai/scripts/citysim_cleanup_check.py --root .` for reference-based candidates.
- Run `.ai/scripts/citysim_find_references.py --root . --symbol SYMBOL` before deleting files or methods.
- Run focused tests after every cleanup.
"""
    write_text(index_dir / "unused_candidates.md", content)


def write_cleanup_plan(index_dir: Path) -> None:
    content = """# Cleanup Plan

Generated by `.ai/scripts/citysim_project_scan.py`.

## Workflow

1. Run `python .ai/scripts/citysim_project_scan.py --root .` to refresh the compact index.
2. Search Qdrant for existing architecture decisions and known bugs.
3. Check `C:\\dev\\projects\\ai_brain\\30_Projects\\Godot City Sim` only for relevant human-readable decisions.
4. Use `citysim_find_references.py` before changing or deleting symbols.
5. Use `citysim_cleanup_check.py` for candidate cleanup reports.
6. Change code only after local files and project memory agree on ownership.

## Deletion Rules

- Never delete a candidate based only on filename.
- Search references in `.gd`, `.tscn`, `.tres`, config JSON, Markdown, and tests.
- Check `load`, `preload`, `class_name`, and `res://` scene paths.
- Run focused tests after removal.
- Record durable cleanup decisions in Obsidian only when they matter beyond the immediate change.

## Immediate Cleanup Targets

- Keep `.claude`, `.godot`, `.obsidian`, `.ai/.cache`, and Qdrant storage out of scans.
- Audit legacy-vs-new citizen paths with reference searches.
- Audit `Actions/*` vs `Simulation/GOAP/*` before adding behavior.
- Audit imported city source separately from active runtime code.
"""
    write_text(index_dir / "cleanup_plan.md", content)


def ensure_architecture_decisions(index_dir: Path) -> None:
    path = index_dir / "architecture_decisions.md"
    if path.exists():
        return
    content = """# Architecture Decisions

Purpose: human-curated decisions that should be checked before architectural edits.

## Memory

- Use local files and `.ai/project_index/` before broad context loading.
- Use Qdrant for short searchable facts, not full files.
- Use `C:\\dev\\projects\\ai_brain\\30_Projects\\Godot City Sim` as the Obsidian project-memory folder.
"""
    write_text(path, content)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Project root or any path inside it.")
    parser.add_argument("--dry-run", action="store_true", help="Print summary without writing index files.")
    args = parser.parse_args()

    root = resolve_project_root(args.root)
    files = iter_project_files(root)
    index_dir = root / INDEX_DIR

    print(f"Project root: {root}")
    print(f"Indexed files: {len(files)}")
    print("Top folders:")
    for folder, count in sorted(Counter(top_folder(file.rel) for file in files).items()):
        print(f"  {folder}: {count}")

    if args.dry_run:
        return 0

    write_files_index(root, files, index_dir)
    write_systems_index(files, index_dir)
    write_duplicated_logic_index(files, index_dir)
    write_unused_candidates_index(root, files, index_dir)
    write_cleanup_plan(index_dir)
    ensure_architecture_decisions(index_dir)
    print(f"Wrote compact index to {index_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
