#!/usr/bin/env python
"""Find cleanup candidates without leaving the Godot project root."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

from citysim_common import (
    ProjectFile,
    count_lines,
    count_literal_references,
    extract_gdscript_symbols,
    iter_project_files,
    load_text_corpus,
    markdown_table,
    resolve_project_root,
    write_text,
)


def find_duplicate_stems(files: list[ProjectFile]) -> list[tuple[str, int, str]]:
    groups: dict[str, list[str]] = defaultdict(list)
    for file in files:
        if file.extension in {".gd", ".tscn", ".tres"}:
            groups[file.path.stem.lower()].append(file.rel)
    return [
        (stem, len(rels), "<br>".join(rels[:10]))
        for stem, rels in sorted(groups.items())
        if len(rels) > 1
    ]


def find_large_files(files: list[ProjectFile], min_lines: int) -> list[tuple[str, int, int]]:
    rows = []
    for file in files:
        lines = count_lines(file.path)
        if lines >= min_lines:
            rows.append((file.rel, lines, file.size))
    return sorted(rows, key=lambda row: row[1], reverse=True)


def find_reference_candidates(root: Path, files: list[ProjectFile], max_results: int) -> list[tuple[str, str, int, int]]:
    corpus = load_text_corpus(root)
    rows: list[tuple[str, str, int, int]] = []

    for file in files:
        if file.extension not in {".gd", ".tscn", ".tres"}:
            continue
        rel = file.rel
        res_path = "res://" + rel
        path_refs = count_literal_references(corpus, res_path, exclude_rel=rel)
        basename_refs = count_literal_references(corpus, file.path.name, exclude_rel=rel)

        symbols = extract_gdscript_symbols(file.path) if file.extension == ".gd" else {"class_names": []}
        class_refs = 0
        for class_name in symbols["class_names"]:
            class_refs += count_literal_references(corpus, class_name, exclude_rel=rel)

        if path_refs == 0 and class_refs == 0 and basename_refs <= 1:
            rows.append((rel, "low references; verify before deleting", path_refs, class_refs))

        if len(rows) >= max_results:
            break

    return rows


def build_report(root: Path, min_lines: int, max_reference_candidates: int) -> str:
    files = iter_project_files(root)
    duplicate_stems = find_duplicate_stems(files)
    large_files = find_large_files(files, min_lines=min_lines)
    reference_candidates = find_reference_candidates(root, files, max_results=max_reference_candidates)

    local_dirs = []
    for rel in [".claude", ".godot", ".idea", ".obsidian", "AI", "AI_RuntimeTest"]:
        path = root / rel
        if path.exists():
            local_dirs.append((rel, "excluded from normal scans"))

    return f"""# Cleanup Check

Generated by `.ai/scripts/citysim_cleanup_check.py`.

Project root: `{root}`

## Local Or Generated Directories

{markdown_table(["Path", "Reason"], local_dirs) if local_dirs else "No local/generated directories detected."}

## Duplicate File Stems

{markdown_table(["Stem", "Count", "Examples"], duplicate_stems[:80]) if duplicate_stems else "No duplicate file stems detected."}

## Large Files

{markdown_table(["Path", "Lines", "Bytes"], large_files[:50]) if large_files else f"No files above {min_lines} lines detected."}

## Low-Reference Candidates

These are weak candidates only. Dynamic Godot loading, `class_name`, scene paths, and tests must be checked before deletion.

{markdown_table(["Path", "Reason", "res:// refs", "class refs"], reference_candidates) if reference_candidates else "No low-reference candidates detected."}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Project root or any path inside it.")
    parser.add_argument("--min-lines", type=int, default=500)
    parser.add_argument("--max-reference-candidates", type=int, default=80)
    parser.add_argument("--write-index", action="store_true", help="Write report to .ai/project_index/unused_candidates.md.")
    args = parser.parse_args()

    root = resolve_project_root(args.root)
    report = build_report(root, args.min_lines, args.max_reference_candidates)
    if args.write_index:
        output = root / ".ai/project_index/unused_candidates.md"
        write_text(output, report)
        print(f"Wrote cleanup report to {output}")
    else:
        print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
